### PR TITLE
Update to use hooks

### PR DESCRIPTION
**Pull request by michaltk**
- removes deprecated react lifecycles
- update all dependencies

It exports both the new `useMailCheck` hook and also old that `MailCheck` that uses render prop (which internally now uses the same `useMailCheck` hook.)

### CODE REVIEW

**Comment by eligolding** [comment]
Thanks @michaltk! Can you update the readme as well?

**Comment by michaltk** [comment]
Was going to leave that to your expertise…

**Comment by michaltk** [comment]
> update all dependencies

Really babel is not updated to the latest.. v7 babel deps are `@babel/..`
but the presets you are using are deprecated on v7, so was thinking to change to use https://github.com/palmerhq/tsdx perhaps.

**Comment by eligolding** [comment]
>Was going to leave that to your expertise…

Do you not know me? 😜 

>the presets you are using are deprecated on v7

Are there equivalents that are compatible? 

>was thinking to change to use https://github.com/palmerhq/tsdx

I'm fine with that.

**Comment by bartkoedijk** [comment]
Can we merge this? I am getting a warning about the componentWillMount() method that it's still being used.

**Comment by michaltk** [comment]
Updated with hooks here: https://github.com/qualitybath/use-mailcheck

**Comment by KevinDanikowski** [comment]
I'm surprised this isn't merged yet. I copied the code directly into my project

**Pull request closed without merging**
