### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by lancecarlson**
Add threshold configuration

### CODE REVIEW

**Comment by lancecarlson** [comment]
@eligolding Any objections to this? :smile:

**Comment by eligolding** [comment]
I'm not saying that i'm for sure against this, but my hesitation is that changing the threshold is not really one of the public options of mailcheck.

**Comment by eligolding** [comment]
Though I guess even though they're are not options to the `run` function, mailcheck still gives you the option to change the properties on the mailcheck object. Ok, I'm gonna merge this.

**Comment by eligolding** [comment]
@lancecarlson thanks!

**Comment by lancecarlson** [comment]
@eligolding No problem! I had to adjust this on my project because the defaults didn't make sense. Looking at what Lyft did, it looks like they also had to adjust the defaults to something that made more sense.

**Pull request merged**
